[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
bethehouse = "Au4V34qyUhMfAL9HfC3QLTtTi6Mua7WdqDYUdZqhEdGS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm vitest run"
